export { HookRegistry, createHookRegistry } from './hook-registry'
export type { HookPreset, HookRegistryOptions } from './hook-registry'

export { safeCreateHook, isHookEnabled } from './safe-hook'

export { defineHook } from './hook-spec'
export type { HookSpec } from './hook-spec'

export {
  createFirstMessageVariantHook,
  createSessionRecoveryHook,
  createKeywordDetectionHook,
  createSessionHistoryHook,
  createIdleContinuationHook,
  createErrorRecoveryHook,
  resetErrorRecoveryCounter,
  createFileGuardHook,
  createLabelTruncatorHook,
  createRulesInjectorHook,
  createOutputTruncationHook,
  createToolOutputPersistenceHook,
  createContextInjectorHook,
  createThinkingValidatorHook,
  createAnthropicEffortHook,
  createCommentCheckerHook,
  createBabysittingHook,
  createRalphLoopHook,
  createPatchReviewGateHook,
  // Stream 生命周期
  createStreamMetricsHook,
  createStreamEndMetricsHook,
  getStreamMetrics,
  clearStreamMetrics,
  // Compaction 生命周期
  createCompactionLoggerHook,
  createCompactionAfterHook,
  getCompactionStats,
  clearCompactionStats,
  // Background 生命周期
  createBackgroundStartHook,
  createBackgroundEndHook,
  getActiveBackgroundTasks,
  getCompletedBackgroundTasks,
  clearBackgroundTaskHistory,
  // Tool 错误追踪
  createToolErrorTrackerHook,
  getToolErrors,
  clearToolErrors,
  // Token 预算
  createTokenBudgetHook,
  trackTokenUsage,
  getTokenUsage,
  clearTokenUsage,
  createCommandHook,
  isCommandHookConfig,
} from './core'
export type {
  ContextInjectorConfig,
  ContextProvider,
  IdleContinuationConfig,
  ErrorRecoveryConfig,
  ToolErrorTrackerConfig,
  ToolOutputPersistenceConfig,
  TokenBudgetConfig,
  PatchReviewGateConfig,
  PatchReviewSummary,
  CommandHookConfig,
  CommandHookMatcher,
  CommandHookRunner,
  CommandHookRunInput,
  CommandHookRunResult,
} from './core'

// Permission
export {
  PermissionPolicyRegistry,
  PermissionAuditLog,
  PermissionGuardHook,
  compilePolicyFromSetting,
  createPermissionGuardHook,
  FILE_GUARD_POLICY,
  DESTRUCTIVE_COMMAND_POLICY,
  createFileGuardPolicy,
  createPermissionToolSetsFromRegistry,
  createDirectoryFreezePolicy,
  createDisabledToolsPolicy,
  createAgentBoundaryPolicy,
  createSidechainBoundaryPolicy,
  createPermissionModePolicy,
  createPermissionRegistry,
} from './core'
export type {
  RuleEffect,
  PermissionMode,
  PolicyScope,
  PermissionContext,
  RuleMatch,
  PermissionRule,
  PermissionPolicy,
  PermissionDecision,
  PermissionAuditEntry,
  PermissionRuleConfig,
  PermissionPolicySetting,
  PermissionToolDescriptor,
  PermissionToolSets,
  PermissionToolSetsInput,
} from './core'

export type {
  HookTiming,
  HookInput,
  HookOutput,
  HookHandle,
  ObserverTiming,
  InterceptorTiming,
  HookPayloadMap,
  ChatMessageInput,
  ChatMessageOutput,
  ToolExecuteBeforeInput,
  ToolExecuteBeforeOutput,
  ToolExecuteAfterInput,
  ToolExecuteAfterOutput,
  MessagesTransformInput,
  MessagesTransformOutput,
  ChatParamsInput,
  ChatParamsOutput,
  SystemPromptTransformInput,
  SystemPromptTransformOutput,
  SystemPromptSectionLayer,
  SystemPromptSection,
  SystemPromptSectionDiagnostic,
  SystemPromptAssembly,
  SystemPromptAssemblyDiagnostics,
  SystemPromptSectionsTransformInput,
  SystemPromptSectionsTransformOutput,
  SessionEventInput,
} from './types'
