#!/usr/bin/env tsx
// scripts/generate-models.ts
// Phase 3 基础设施 — 模型清单自动生成脚本
//
// 用法: pnpm --filter @x-mars/ai generate:models
//
// 当前为占位实现。正式启用后，此脚本将:
// 1. 从各 Provider API 或本地元数据文件拉取模型列表
// 2. 规范化为 @x-mars/ai Model 接口
// 3. 写入 src/models/models.generated.ts
// 4. 运行 typecheck 确保导出类型正确
//
// 输出文件格式:
//   export const ALL_MODELS: Model[] = [ ... ]

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT = resolve(__dirname, '../src/models/models.generated.ts')

// ── Provider 元数据源（按需扩展） ──
// 每个 source 实现 fetchModels() → Model[]，后续按需添加。
// 示例: GitHub Copilot 可调 GET /models 获取可用模型列表。

function main() {
  console.log('[generate-models] Phase 3 placeholder — no-op')
  console.log('[generate-models] Output target:', OUTPUT)
  console.log('[generate-models] To enable, implement provider metadata sources in this script.')

  // 写入占位文件
  const content = [
    '// AUTO-GENERATED — DO NOT EDIT',
    '// Generated by scripts/generate-models.ts',
    `// Last generated: ${new Date().toISOString()}`,
    '',
    "import type { Model } from '../types'",
    '',
    '// Phase 3 placeholder: 启用后此数组将包含从上游生成的全量模型定义',
    'export const ALL_MODELS: Model[] = []',
    '',
  ].join('\n')

  writeFileSync(OUTPUT, content, 'utf-8')
  console.log('[generate-models] Wrote placeholder to', OUTPUT)
}

main()
